### ISSUE TITLE
Not reporting bug

### ISSUE THREAD

**Issue by Just1C3-2** [DorkixAzIgazi/NetheriteCompass#11]
Could you make a Emerald Compass?

**Comment by DorkixAzIgazi** [comment]
> Could you make a Emerald Compass?

It wouldn't be hard, but this mod might work better, seems quiet configurable
https://modrinth.com/mod/miners-compass

**Comment by Just1C3-2** [comment]
yeah but im playing 1.21 and this mod only have 1.20.x,anyway thanks for reply
