### ISSUE TITLE
I have no idea what is this

### ISSUE THREAD

**Issue by Just1C3-2** [DorkixAzIgazi/NetheriteCompass#12]
just see the screenshot
![2024-08-23_12 44 28](https://github.com/user-attachments/assets/9eff1805-7760-4257-a51e-46595926f76a)

**Comment by DorkixAzIgazi** [comment]
> just see the screenshot
> ![2024-08-23_12 44 28](https://github.com/user-attachments/assets/9eff1805-7760-4257-a51e-46595926f76a)
> 
> 

Interesting... Never seen it before. Let me know if you find out what causes it.

**Comment by Just1C3-2** [comment]
Yeah i thought it was clear in that screenshots......
when you equip compass in your offhand and right click with a stuff in mainhand,both items will display Locating.....
its kinda weird when i first find out honesty

**Comment by DorkixAzIgazi** [comment]
Thats weird, that description is applied with the lore (description) item component, which is a minecraft feature, its either a minecraft or fabric bug or caused by some other mod. I'll look into it later today if i have the time.
