### ISSUE TITLE
Compass3D Support

### ISSUE THREAD

**Issue by AdamRaichu** [DorkixAzIgazi/NetheriteCompass#4]
Hey, I just wanted to let you know that I added support for this mod to my mod [Compass3D](https://modrinth.com/mod/compass3d). Compass3D is a client-side mod that adds an overlay arrow to compasses to indicate the y-direction of the target, to make it easier to find the target. Happy modding! :D

**Comment by DorkixAzIgazi** [comment]
@AdamRaichu I have updated the mod to minecraft 1.20.4. Works perfectly with your latest release!😄
