### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Just1C3-2** [DorkixAzIgazi/NetheriteCompass#5]
I'm using the latest version but it doesn't work. The compass is only get lock when ancient debris is exposed. I also got some optimization mods as well so I'm not sure if it's a bug in the mod itself or if it's just incompatible with other mods

**Comment by DorkixAzIgazi** [comment]
Can you give me more details, like the minecraft version and mod versions you are using? Optimazition mod could be a problem if they prevent nearby chunks from loading. Also please make sure you are familiar with how the locking mechanic works, you can read all you need in the README file.

**Comment by Just1C3-2** [comment]
farbic 1.20.1 netherrite compass 1.0.1
about optimzaition mod im using
c^2m lithium sodium mordenfix starlight indium
that is all

**Comment by DorkixAzIgazi** [comment]
> farbic 1.20.1 netherrite compass 1.0.1 about optimzaition mod im using c^2m lithium sodium mordenfix starlight indium that is all

![image](https://github.com/DorkixAzIgazi/NetheriteCompass/assets/53568132/aa3aa5b4-08c8-450f-b61f-60224a5d5d1d)
I've tried this with a fresh minecraft install, with these mod versions, created a new default world in creative, went to the nether and started using the compass, worked just fine for me, on level 15 it pointed to the nearest Ancient Debris. I found 5 one after the other which were not exposed.
 
Note, I didn't change any setting for the mods. If you share your settings for the mods and/or provide a world seed with location or a world download, where you think the mod doesn't work, I could take another look. I didn't find any compatibility issues this time.

I might update the mod to 1.20.4, if I have the time.

**Comment by Just1C3-2** [comment]
I created another world in creative mode,and guess what? it worked.
After that I experimented again on the previous world which it didn't work, but idk why it still didn't work???
Now I have absolutely no freaking idea how this happens.
should this only work in new world before the mod was added?

**Comment by Just1C3-2** [comment]
and i think i found why,i think im a totally dumb.
when a chunk is generated before this mod added,this compass didnt work.
and this is because what u said in readme:The mod will turn the Ancient Debris block into a Block entity (like a chest or furnace). Altought this sounds strange, it does not affect its behaviour in any way, but helps the mod perform much better as it only needs to look at block entities in the chunk not all blocks. Minecraft's code already handles block entities differently than blocks, the mod only filters for a certain type (Ancient Debris) and finds the clossest one to the player.
i think that is it.sorry for wasting your time

**Comment by Just1C3-2** [comment]
there is some screen shots
![2024-03-25_13 54 20](https://github.com/DorkixAzIgazi/NetheriteCompass/assets/80753166/e05a40e7-9cde-4170-8884-cc4d7da88a4f)
![2024-03-25_13 54 23](https://github.com/DorkixAzIgazi/NetheriteCompass/assets/80753166/e21dc6fc-2bd2-4d46-aa75-ace43ea99559)
![2024-03-25_13 54 31](https://github.com/DorkixAzIgazi/NetheriteCompass/assets/80753166/9b339666-a4f9-4ec0-9ddd-ae36ad0e810b)
![2024-03-25_13 54 35](https://github.com/DorkixAzIgazi/NetheriteCompass/assets/80753166/3a65e5c9-154c-4739-8847-6ccad46102bf)
and you could see in the last picture,once i could touch(or reach)that block,the compass instantly get locked on it

**Comment by DorkixAzIgazi** [comment]
> and i think i found why,i think im a totally dumb.
> when a chunk is generated before this mod added,this compass didnt work.
> and this is because what u said in readme:The mod will turn the Ancient Debris block into a Block entity (like a chest or furnace). Altought this sounds strange, it does not affect its behaviour in any way, but helps the mod perform much better as it only needs to look at block entities in the chunk not all blocks. Minecraft's code already handles block entities differently than blocks, the mod only filters for a certain type (Ancient Debris) and finds the clossest one to the player.
> i think that is it.sorry for wasting your time

This is instresting this could be a problem. I could see Ancient Debris in old chunks not turning into block entities, as when a save is loaded they are saved as normal blocks, I think? I am not sure how this works when the world is saved or loaded. I'll look into in a few days.

**Comment by DorkixAzIgazi** [comment]
I can confirm that the above is the case. Ancient Debris blocks generated in the world before the mod was added are not detected by compass. This should not be the case, you should be able to just add the mod and use it with you existing worlds. 

I do not know the solution for this, but I'll try to think of something in the following days. Feel free to comment if you can think of anything to fix this. 

Thanks for you patience.

**Comment by DorkixAzIgazi** [comment]
@Just1C3-2 Hi, I finally got around to fix this issues feel free to contact me if you find anything else :D 
[release](https://github.com/DorkixAzIgazi/NetheriteCompass/releases/tag/v1.3.0-fabric-1.21)
